# Generated by Django 5.0.6 on 2024-07-07 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_reactor_no', models.CharField(max_length=100)),
                ('reactor_name', models.CharField(max_length=100)),
                ('reactor_type', models.CharField(max_length=100)),
                ('sap_material_no', models.CharField(max_length=100)),
                ('recipe_id', models.CharField(max_length=100)),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_version', models.CharField(max_length=100)),
                ('recipe_last_change', models.DateTimeField()),
                ('timestamp_recipe_start', models.DateTimeField()),
                ('timestamp_start_filling', models.DateTimeField()),
                ('timestamp_end_filling', models.DateTimeField()),
                ('timestamp_start_reaction', models.DateTimeField()),
                ('timestamp_end_reaction', models.DateTimeField()),
                ('timestamp_start_heating', models.DateTimeField()),
                ('timestamp_end_heating', models.DateTimeField()),
                ('timestamp_start_cooling', models.DateTimeField()),
                ('timestamp_end_cooling', models.DateTimeField()),
                ('timestamp_start_additivation', models.DateTimeField()),
                ('timestamp_end_additivation', models.DateTimeField()),
                ('timestamp_start_sampling', models.DateTimeField()),
                ('timestamp_end_sampling', models.DateTimeField()),
                ('timestamp_start_adjusting', models.DateTimeField()),
                ('timestamp_end_adjusting', models.DateTimeField()),
                ('timestamp_start_filling_2', models.DateTimeField()),
                ('timestamp_end_filling_2', models.DateTimeField()),
                ('timestamp_recipe_end', models.DateTimeField()),
                ('product_5_before_batch', models.CharField(max_length=100)),
                ('product_4_before_batch', models.CharField(max_length=100)),
                ('product_3_before_batch', models.CharField(max_length=100)),
                ('product_2_before_batch', models.CharField(max_length=100)),
                ('product_before_batch', models.CharField(max_length=100)),
                ('product_after_batch', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('name_of_site', models.CharField(max_length=100)),
                ('process_order_no', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=100)),
                ('control_config_1', models.CharField(max_length=100)),
                ('control_config_2', models.CharField(max_length=100)),
                ('control_config_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDataHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(help_text='Unique header name.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Process Data Header',
                'verbose_name_plural': 'Process Data Headers',
                'ordering': ['header_name'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File to be uploaded.', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the file was uploaded.')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Timestamp of the data.')),
                ('value', models.FloatField(default=0.0, help_text='Value of the data.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('batch_no', models.ForeignKey(help_text='Batch number related to this process data.', on_delete=django.db.models.deletion.CASCADE, related_name='process_data', to='processV.generaldata')),
                ('header', models.ForeignKey(help_text='Header related to this process data.', on_delete=django.db.models.deletion.CASCADE, related_name='process_data', to='processV.processdataheader')),
            ],
            options={
                'verbose_name': 'Process Data',
                'verbose_name_plural': 'Process Data',
                'ordering': ['timestamp'],
            },
        ),
    ]
