# Generated by Django 5.0.6 on 2024-07-07 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processdataheader',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='processdataheader',
            name='header_name',
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='max_value_pcs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='min_value_pcs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='tag_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='type_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processdataheader',
            name='value_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processV.generaldata'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processV.processdataheader'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
