# Generated by Django 5.0.6 on 2024-07-07 22:59

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0003_alter_generaldata_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdataheader',
            name='row',
            field=models.IntegerField(default=0),  # Set an appropriate integer default value
        ),
    ]
