# Generated by Django 5.0.6 on 2024-07-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0004_processdataheader_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdataheader',
            name='row',
        ),
    ]
