# Generated by Django 5.0.6 on 2024-07-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0005_remove_processdataheader_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdataheader',
            name='row',
            field=models.IntegerField(default=0, verbose_name='Row Number'),
        ),
    ]
