# Generated by Django 5.0.6 on 2024-07-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0006_processdataheader_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processdata',
            options={'ordering': ['timestamp'], 'verbose_name': 'Process Data', 'verbose_name_plural': 'Process Data'},
        ),
    ]
