# Generated by Django 5.0.6 on 2024-07-08 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0007_alter_processdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdata',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='i_homog',
            field=models.FloatField(default=0.0, verbose_name='Homogenizer Current'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='i_stirrer',
            field=models.FloatField(default=0.0, verbose_name='Stirrer Current'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='n_homog',
            field=models.FloatField(default=0.0, verbose_name='Homogenizer Speed'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='n_homog_target',
            field=models.FloatField(default=0.0, verbose_name='Homogenizer Speed Target'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='n_stirrer',
            field=models.FloatField(default=0.0, verbose_name='Stirrer Speed'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='n_stirrer_target',
            field=models.FloatField(default=0.0, verbose_name='Stirrer Speed Target'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='p_reactor',
            field=models.FloatField(default=0.0, verbose_name='Reactor Pressure'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='p_reactor_target',
            field=models.FloatField(default=0.0, verbose_name='Reactor Pressure Target'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='pos_mh',
            field=models.IntegerField(default=0, verbose_name='Manhole Position'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='recipe_step',
            field=models.IntegerField(default=0, verbose_name='Recipe Step'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='t_hotoil_in',
            field=models.FloatField(default=0.0, verbose_name='Hot Oil Inlet Temperature'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='t_hotoil_in_target',
            field=models.FloatField(default=0.0, verbose_name='Hot Oil Inlet Temperature Target'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='t_hotoil_out',
            field=models.FloatField(default=0.0, verbose_name='Hot Oil Outlet Temperature'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='t_reactor',
            field=models.FloatField(default=0.0, verbose_name='Reactor Temperature'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='t_reactor_target',
            field=models.FloatField(default=0.0, verbose_name='Reactor Temperature Target'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='v_exh',
            field=models.FloatField(default=0.0, verbose_name='Exhaust Valve'),
        ),
    ]
