# Generated by Django 5.0.6 on 2024-07-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processV', '0008_processdata_date_time_processdata_i_homog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdata',
            name='header',
        ),
    ]
